"""initial_schema

Revision ID: bd4839f96b99
Revises:
Create Date: 2026-07-07 01:43:04.245649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd4839f96b99"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent_checkpoints",
        "session_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "agent_checkpoints", "current_step", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "agent_checkpoints", "state_json", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "agent_checkpoints", "trajectory_json", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "agent_checkpoints",
        "updated_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "conversation_history",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "conversation_history",
        "session_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "conversation_history",
        "role",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        nullable=False,
    )
    op.alter_column(
        "conversation_history", "content", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "conversation_history",
        "timestamp",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.create_index(
        op.f("ix_conversation_history_session_id"),
        "conversation_history",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_history_session_id"), table_name="conversation_history"
    )
    op.alter_column(
        "conversation_history",
        "timestamp",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "conversation_history", "content", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "conversation_history",
        "role",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "conversation_history",
        "session_id",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "conversation_history",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "agent_checkpoints",
        "updated_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "agent_checkpoints", "trajectory_json", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "agent_checkpoints", "state_json", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "agent_checkpoints", "current_step", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "agent_checkpoints",
        "session_id",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###
